fixtures:
  repositories:
    # apache:
    #   repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
    #   ref:  '1.0.1'
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref:  '4.4.0'
    ssh:
      repo: 'saz/ssh'
      ref:  '2.5.0'
  symlinks:
    keymaster: "#{source_dir}"
