language: ruby
# sudo: false
bundler_args: --without development
before_install:
# Make a whole bunch files to test against
  - sudo mkdir -p /var/lib/keymaster/openssh/tester_at_test.example.org
  - sudo mkdir -p /var/lib/keymaster/host_key/test.example.org
  - sudo mkdir -p /var/lib/keymaster/x509/test.example.org
  - sudo sh -c "echo '-----BEGIN RSA PRIVATE KEY-----THISISAFAKERSAHASH-----END RSA PRIVATE KEY-----' > /var/lib/keymaster/openssh/tester_at_test.example.org/key"
  - sudo sh -c "echo 'ssh-rsa THISISAFAKERSAHASH foo@baa' > /var/lib/keymaster/openssh/tester_at_test.example.org/key.pub"
  - sudo sh -c "echo '-----BEGIN RSA PRIVATE KEY-----THISISAFAKERSAHASH-----END RSA PRIVATE KEY-----' > /var/lib/keymaster/host_key/test.example.org/key"
  - sudo sh -c "echo 'ssh-rsa THISISAFAKERSAHASH foo@baa' > /var/lib/keymaster/host_key/test.example.org/key.pub"
  - sudo sh -c "echo '-----BEGIN RSA PRIVATE KEY-----THISISAFAKERSAHASH-----END RSA PRIVATE KEY-----' > /var/lib/keymaster/x509/test.example.org/key.pem"
  - sudo sh -c "echo '-----BEGIN CERTIFICATE REQUEST-----THISISAFAKEHASH-----END CERTIFICATE REQUEST-----' > /var/lib/keymaster/x509/test.example.org/request.csr"
  - sudo sh -c "echo '-----BEGIN CERTIFICATE-----THISISAFAKEHASH-----END CERTIFICATE-----' > /var/lib/keymaster/x509/test.example.org/certificate.crt"
  - sudo sh -c "echo '-----BEGIN CERTIFICATE-----THISISAFAKEPEM-----END CERTIFICATE-----' > /var/lib/keymaster/x509/test.example.org/certificate.pem"
  - sudo sh -c "echo '-----BEGIN CERTIFICATE-----THISISAFAKEP12-----END CERTIFICATE-----' > /var/lib/keymaster/x509/test.example.org/certificate.p12"
  - sudo sh -c "echo '-----BEGIN CERTIFICATE-----THISISAFAKEPFX-----END CERTIFICATE-----' > /var/lib/keymaster/x509/test.example.org/certificate.pfx"
before_script:
  - bundle exec metadata-json-lint metadata.json
  - bundle exec rake validate_ruby_syntax
  - bundle exec rake check_line_endings
  - bundle exec rake syntax
  - bundle exec rake lint

script:
  - bundle exec rake spec SPEC_OPTS='--format documentation'

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.4

env:
  matrix:
  - PUPPET_GEM_VERSION="~> 2.6.0"
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
  - PUPPET_GEM_VERSION="~> 3.5.0"
  - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.6.0"
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES="yes"

matrix:
  fast_finish: true
  # sax-ssh fails STRICT_VARIABLES
  allow_failures:
    - env: PUPPET_GEM_VERSION="~> 2.6.0"
    - env: PUPPET_GEM_VERSION="~> 2.7.0"
    - env: PUPPET_GEM_VERSION="~> 3.0.0"
    - env: PUPPET_GEM_VERSION="~> 3.1.0"
    - env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
    - env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
    - env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
    - env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES="yes"
    - rvm: 2.2.4
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.4.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.2.4
      env: PUPPET_GEM_VERSION="~> 3.4.0"

notifications:
  email: false